### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by set321go** [BarcodeEye/BarcodeEye#6]
Looks like all commits were made a couple of months ago with nothing in between. 

@paulpv and @pub-burrito you seem to have the only forks with any activity. Have either of you done any work on Issue  #1 ? Looking for something that scans a barcode then hands the result back to me.

**Comment by jromero** [comment]
Unfortunately due to the bugs that Google glass currently has that the
Google team has not resolved this project is currently in the back burner.
The bugs primarily revolve around how the camera functions and is unable to
properly detect barcodes within reason. Unlike zxing, this project will not
be cross application intent driven, instead I have plans to allow this
project to be used as a library so you can simply use the scanner as you
would any other Activity within your application.

**Comment by set321go** [comment]
Thanks for the response. I found a couple of threads which your probably talking about
https://groups.google.com/forum/#!topic/zxing/P-QLWhlB_wU
https://groups.google.com/forum/#!msg/zxing/DjkgCBr2Ehc/wJ4-41vPvvQJ

**Comment by jromero** [comment]
The second issue already has a work around.

To be specific, there are 3.
1. Focus mode can't be changed
2. Scene mode can't be changed
3. They refused the the "Scan a barcode" trigger stating that "Scan a
   product" should suffice even after explaining the different type of
   barcodes available.

**Comment by set321go** [comment]
So i see what your on about now, i took @pub-burrito's fork and embedded the library into my app, made a couple of changes to the capture activity to return the results and now i can scan a barcode but only when its about 1 maybe 2 feet in front of my face, not ideal really!!

https://code.google.com/p/google-glass-api/issues/detail?id=344&q=camera&colspec=ID%20Type%20Status%20Priority%20Owner%20Component%20Summary

https://code.google.com/p/google-glass-api/issues/detail?id=303&q=camera&colspec=ID%20Type%20Status%20Priority%20Owner%20Component%20Summary
